apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: syfobrukertilgang-alerts
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  groups:
    - name: syfobrukertilgang-alerts
      rules:
        - alert: SYFOBRUKERTILGANG IS DOWN!
          expr: kube_deployment_status_replicas_available{deployment="syfobrukertilgang"} == 0
          for: 5m
          annotations:
            summary: "App syfobrukertilgang er nede i namespace {{ $labels.namespace }}"
            action: "Undersøk hvofor syfobrukertilgang er nede i prod-fss"
          labels:
            namespace: team-esyfo
            severity: critical
        - alert: HIGH RATIO OF HTTP 5XX RESPONSE
          expr: (100 * (sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", status=~"^5\\d\\d", service="syfobrukertilgang"}[5m])) / sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", service="syfobrukertilgang"}[5m])))) > 2
          for: 5m
          annotations:
            summary: "App syfobrukertilgang har en høy andel 500 feil {{ $labels.namespace }}"
            action: "Sjekk i Grafana eller logger at syfobrukertilgang returnerer mange 500-feil"
          labels:
            namespace: team-esyfo
            severity: warning
        - alert: HIGH RATIO OF HTTP 4XX RESPONSE
          expr: (100 * (sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", status=~"^4\\d\\d", service="syfobrukertilgang"}[5m])) / sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", service="syfobrukertilgang"}[5m])))) > 10
          for: 5m
          annotations:
            summary: "App syfobrukertilgang har en høy 400 feil {{ $labels.namespace }}"
            action: "Sjekk i Grafana eller logger at syfobrukertilgang returnerer mange 400-feil"
          labels:
            namespace: team-esyfo
            severity: warning
