[tools]
java = "21"

# Quality checks
[tasks.build]
description = "Run build with gradle"
run = './gradlew build'

[tasks.test]
description = "Run tests with gradle"
run = './gradlew test'

[tasks.lint]
description = "Run check with gradle"
run = './gradlew ktlintCheck'

[tasks.format]
description = "Run ktlintFormat with gradle"
run = './gradlew ktlintFormat'
