apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfobrukertilgang
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 768Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfobrukertilgang.nais.adeo.no"
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/prod/creds/syfobrukertilgang
        mountPath: /secrets/azuread/syfobrukertilgang
      - kvPath: /serviceuser/data/prod/srvsyfobrukertilga
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/syfobrukertilgang/default
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  env:
    - name: KTOR_ENV
      value: production
    - name: AAD_ACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: AKTORREGISTER_V1_URL
      value: "https://app.adeo.no/aktoerregister/api/v1"
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: "https://security-token-service.nais.adeo.no"
    - name: SYFONARMESTELEDER_URL
      value: https://syfonarmesteleder.nais.adeo.no
