apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfobrukertilgang
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  team: teamsykefravr
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 256Mi
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfobrukertilgang.nais.preprod.local"
  vault:
    enabled: true
    paths:
      - kvPath: /azuread/data/dev/creds/syfobrukertilgang
        mountPath: /secrets/azuread/syfobrukertilgang
      - kvPath: /serviceuser/data/dev/srvsyfobrukertilga
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/syfobrukertilgang/default
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  env:
    - name: KTOR_ENV
      value: production
    - name: CLIENT_ID
      value: ""
    - name: AADDISCOVERY_URL
      value: ""
    - name: JWT_ISSUER
      value: ""
    - name: AKTORREGISTER_V1_URL
      value: "https://app-q1.adeo.no/aktoerregister/api/v1"
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: "https://security-token-service.nais.preprod.local"
