apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfobrukertilgang
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /is_ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 768Mi
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
    - "https://syfobrukertilgang.intern.dev.nav.no"
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: syfomotebehov
          cluster: dev-fss
        - application: syfomotebehov
          cluster: dev-gcp
        - application: syfooppfolgingsplanservice
          cluster: dev-fss
        - application: oppfolgingsplan-backend
    outbound:
      rules:
        - application: narmesteleder
          namespace: teamsykmelding
          cluster: dev-gcp
        - application: sykmeldinger-arbeidsgiver
          namespace: teamsykmelding
          cluster: dev-gcp
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  env:
    - name: KTOR_ENV
      value: production
    - name: NARMESTELEDER_URL
      value: http://narmesteleder.teamsykmelding
    - name: NARMESTELEDER_SCOPE
      value: api://dev-gcp.teamsykmelding.narmesteleder/.default
