name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
jobs:
  jar-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/jar-app.yaml@main
    permissions:
      actions: read
      contents: write
      security-events: write
      packages: write
      id-token: write
    secrets: inherit
    with:
      app: syfobrukertilgang
