name: Build & Deploy
on: push

jobs:
  jar-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/jar-app.yaml@main
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit
    with:
      app: syfobrukertilgang
